<?php

namespace ContainerNunUU4o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ei8HTkQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ei8HTkQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ei8HTkQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\JoueurRepository', 'getJoueurRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\JoueurRepository',
        ]);
    }
}
