<?php

namespace ContainerWjLsmn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MzPqMfKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mzPqMfK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mzPqMfK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DefaultController::Agents' => ['privates', '.service_locator.0C62ABq', 'get_ServiceLocator_0C62ABqService', true],
            'App\\Controller\\DefaultController::Club' => ['privates', '.service_locator.K0c3qYS', 'get_ServiceLocator_K0c3qYSService', true],
            'App\\Controller\\DefaultController::Joueurs' => ['privates', '.service_locator.Cohq4lT', 'get_ServiceLocator_Cohq4lTService', true],
            'App\\Controller\\DefaultController::Offres' => ['privates', '.service_locator.P1FH6k8', 'get_ServiceLocator_P1FH6k8Service', true],
            'App\\Controller\\DefaultController::un_Agent' => ['privates', '.service_locator.Q39OPkZ', 'get_ServiceLocator_Q39OPkZService', true],
            'App\\Controller\\DefaultController::un_joueur' => ['privates', '.service_locator.Ei8HTkQ', 'get_ServiceLocator_Ei8HTkQService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\DefaultController:Agents' => ['privates', '.service_locator.0C62ABq', 'get_ServiceLocator_0C62ABqService', true],
            'App\\Controller\\DefaultController:Club' => ['privates', '.service_locator.K0c3qYS', 'get_ServiceLocator_K0c3qYSService', true],
            'App\\Controller\\DefaultController:Joueurs' => ['privates', '.service_locator.Cohq4lT', 'get_ServiceLocator_Cohq4lTService', true],
            'App\\Controller\\DefaultController:Offres' => ['privates', '.service_locator.P1FH6k8', 'get_ServiceLocator_P1FH6k8Service', true],
            'App\\Controller\\DefaultController:un_Agent' => ['privates', '.service_locator.Q39OPkZ', 'get_ServiceLocator_Q39OPkZService', true],
            'App\\Controller\\DefaultController:un_joueur' => ['privates', '.service_locator.Ei8HTkQ', 'get_ServiceLocator_Ei8HTkQService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\DefaultController::Agents' => '?',
            'App\\Controller\\DefaultController::Club' => '?',
            'App\\Controller\\DefaultController::Joueurs' => '?',
            'App\\Controller\\DefaultController::Offres' => '?',
            'App\\Controller\\DefaultController::un_Agent' => '?',
            'App\\Controller\\DefaultController::un_joueur' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DefaultController:Agents' => '?',
            'App\\Controller\\DefaultController:Club' => '?',
            'App\\Controller\\DefaultController:Joueurs' => '?',
            'App\\Controller\\DefaultController:Offres' => '?',
            'App\\Controller\\DefaultController:un_Agent' => '?',
            'App\\Controller\\DefaultController:un_joueur' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
