<?php

namespace ContainerWjLsmn1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q39OPkZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q39OPkZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q39OPkZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\AgentRepository',
        ]);
    }
}
