<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWjLsmn1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWjLsmn1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWjLsmn1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWjLsmn1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWjLsmn1\App_KernelDevDebugContainer([
    'container.build_hash' => 'WjLsmn1',
    'container.build_id' => '95378f8e',
    'container.build_time' => 1704920523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWjLsmn1');
